#ifndef SYSVIEW_CONFIG_H_
#define SYSVIEW_CONFIG_H_

#include <SEGGER_SYSVIEW_Conf.g.h> // file generated by a script from json file
#include <peripheral_clk_config.h>

#include "SEGGER_SYSVIEW.h"
#include "SystemView/sysview.h"

/*********************************************************************
 *
 *       Defines, configurable
 *
 **********************************************************************
 */
// The application name to be displayed in SystemViewer
#define SYSVIEW_APP_NAME "Nxg_court"

// The target device name
#define SYSVIEW_DEVICE_NAME "nxg_court atmel_sam0 arm"

// Os Name to find the Os file description `SYSVIEW_OsName.txt`
#define SYSVIEW_PROJECT_NAME "NoOS_NxgCourt"

// Frequency of the timestamp. Must match SEGGER_SYSVIEW_Conf.h
#define SYSVIEW_TIMESTAMP_FREQ (CONF_GCLK_TC4_FREQUENCY)

// System Frequency. SystemcoreClock is used in most CMSIS compatible projects.
#define SYSVIEW_CPU_FREQ (CONF_CPU_FREQUENCY)

// The lowest RAM address used for IDs (pointers)
#define SYSVIEW_RAM_BASE (0x10000000)

/*********************************************************************
 *
 *       Defines, Data Plot
 *
 **********************************************************************
 */
#define TEMP_ID 0
#define HUM_ID 1

#define SYSVIEW_NUM_TASKS 24

#endif
